name = "binary-search"
version = "0.1.0"
defaultTargets = ["BinarySearchTest"]
testDriver = "BinarySearchTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "BinarySearch"

[[lean_exe]]
name = "BinarySearchTest"
root = "BinarySearchTest"
