name = "complex-numbers"
version = "0.1.0"
defaultTargets = ["ComplexNumbersTest"]
testDriver = "ComplexNumbersTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "ComplexNumbers"

[[lean_exe]]
name = "ComplexNumbersTest"
root = "ComplexNumbersTest"
