name = "series"
version = "0.1.0"
defaultTargets = ["SeriesTest"]
testDriver = "SeriesTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "Series"

[[lean_exe]]
name = "SeriesTest"
root = "SeriesTest"
