name = "hamming"
version = "0.1.0"
defaultTargets = ["HammingTest"]
testDriver = "HammingTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "Hamming"

[[lean_exe]]
name = "HammingTest"
root = "HammingTest"
