name = "atbash-cipher"
version = "0.1.0"
defaultTargets = ["AtbashCipherTest"]
testDriver = "AtbashCipherTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "AtbashCipher"

[[lean_exe]]
name = "AtbashCipherTest"
root = "AtbashCipherTest"
