name = "binary-search-tree"
version = "0.1.0"
defaultTargets = ["BinarySearchTreeTest"]
testDriver = "BinarySearchTreeTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "BinarySearchTree"

[[lean_exe]]
name = "BinarySearchTreeTest"
root = "BinarySearchTreeTest"
