name = "square-root"
version = "0.1.0"
defaultTargets = ["SquareRootTest"]
testDriver = "SquareRootTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "SquareRoot"

[[lean_exe]]
name = "SquareRootTest"
root = "SquareRootTest"
