name = "camicia"
version = "0.1.0"
defaultTargets = ["CamiciaTest"]
testDriver = "CamiciaTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "Camicia"

[[lean_exe]]
name = "CamiciaTest"
root = "CamiciaTest"
