name = "perfect-numbers"
version = "0.1.0"
defaultTargets = ["PerfectNumbersTest"]
testDriver = "PerfectNumbersTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "PerfectNumbers"

[[lean_exe]]
name = "PerfectNumbersTest"
root = "PerfectNumbersTest"
