name = "luhn"
version = "0.1.0"
defaultTargets = ["LuhnTest"]
testDriver = "LuhnTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "Luhn"

[[lean_exe]]
name = "LuhnTest"
root = "LuhnTest"
