name = "yacht"
version = "0.1.0"
defaultTargets = ["YachtTest"]
testDriver = "YachtTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "Yacht"

[[lean_exe]]
name = "YachtTest"
root = "YachtTest"
